name: automatic Release

# on: 
#   push:
#     tags:
#     - '*'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install stack
      run: | 
        curl -sSL https://get.haskellstack.org/ | sh
    - name: upload release
      run: | 
        cabal upload -u nalchevanidze -p ${{ secrets.GITHUB_TOKEN }}